framework:
  messenger:
    transports:
      user_events:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.symfony_serializer
        options:
          exchange:
            name: user_events
          queues:
            user_events: ~

    routing:
      App\Message\UserUpdatedEvent: user_events
      App\Message\UserDeletedEvent: user_events
