nelmio_api_doc:
    documentation:
        info:
            title: Money transfer user manager
            description: mannages the users!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
