api_platform:
  title: 'Fund Manager API'
  description: 'Accounts & transfer API'
  version: '1.0.0'
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
  enable_swagger: true
  enable_swagger_ui: true
  enable_entrypoint: true
  enable_docs: true
