api_platform:
  title: 'Fund Manager API'
  description: 'Service responsible for accounts and fund transfers'
  version: '1.0.0'

  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'

  enable_swagger: true
  enable_swagger_ui: true
  enable_entrypoint: true
  enable_docs: true
